### ISSUE TITLE
Auto installing packages

### ISSUE THREAD

**Issue by skyquartam** [ahmed-musallam/AEM-UP#2]
Hi, thanks for your work!
I want to edit your script to install some .zip packages after the initial installation (using cURL), but how can i know when the "real" installation (that is, the one that starts after the "Start the systemd AEM deamon for author and publish" task) is done? The only method I know is to see (in person) when the error.logs stops spitting out lines.

**Comment by skyquartam** [comment]
Ok, the correct method is to put the packages inside crx-quickstart/install folder, and the installation of AEM takes care of installing them after the initial setup.

**Comment by ahmed-musallam** [comment]
@skyquartam yeah, I have not found a good way to wait until AEM has finished setup and is ready to receive packages.

The only other way is what you described, put the packages in the `crx-quickstart/install` I think we *could* wait until  `crx-quickstart` folder is created then run an ansible task to copy packages to install folder. But I have no idea at what time of the installation AEM checks the `install` folder. Worth a shot, if you'd like to make a PR for it :)
